apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-ai-test
  labels:
    app: spring-ai-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-ai-test
  template:
    metadata:
      labels:
        app: spring-ai-test
    spec:
      containers:
        - name: spring-ai-test
          image: yusuf040700/spring-ai-test:1.2
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"