name: Build and Test

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Debug Repository Structure (Optional)
        run: ls -R

      - name: Set Up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'
          cache-dependency-path: 'pom.xml'  # FIXED: Use correct path

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Run Tests
        run: mvn test

      - name: Archive Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: app-artifact
          path: target/*.jar  # Adjust if JAR is elsewhere